// <auto-generated />
using System;
using HomeworkApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeworkApi.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20230111031935_initialData")]
    partial class initialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeworkApi.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("peso")
                        .HasColumnType("integer");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("199bd2f7-4732-4493-a8eb-40bd19c303d3"),
                            Nombre = "Actividades Pendientes",
                            peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("199bd2f7-4732-4493-a8eb-40bd19c30302"),
                            Nombre = "Actividades Personales",
                            peso = 50
                        });
                });

            modelBuilder.Entity("HomeworkApi.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("199bd2f7-4732-4493-a8eb-40bd19c30304"),
                            CategoriaId = new Guid("199bd2f7-4732-4493-a8eb-40bd19c303d3"),
                            Estado = "Pendiente",
                            FechaCreacion = new DateTime(2023, 1, 10, 22, 19, 35, 692, DateTimeKind.Local).AddTicks(4137),
                            Prioridad = 2,
                            Titulo = "Pago de servicios publicos"
                        },
                        new
                        {
                            TareaId = new Guid("199bd2f7-4732-4493-a8eb-40bd19c30305"),
                            CategoriaId = new Guid("199bd2f7-4732-4493-a8eb-40bd19c30302"),
                            Estado = "Pendiente",
                            FechaCreacion = new DateTime(2023, 1, 10, 22, 19, 35, 692, DateTimeKind.Local).AddTicks(4150),
                            Prioridad = 1,
                            Titulo = "Terminar de ver pelicula en netflic"
                        });
                });

            modelBuilder.Entity("HomeworkApi.Models.Tarea", b =>
                {
                    b.HasOne("HomeworkApi.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("HomeworkApi.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
